# Generated by Django 3.1.5 on 2021-01-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210130_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='NlpResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CVE')),
                ('cwe', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CWE')),
                ('software', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='SOFTWARE')),
                ('malware', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='MALWARE')),
                ('course_of_action', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='COURSE_OF_ACTION')),
                ('intrusion_set', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='INTRUSION_SET')),
                ('threat_actor', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='THREAT_ACTOR')),
                ('tool', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='TOOL')),
                ('attack_pattern', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ATTACK_PATTERN')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='INDUSTRY')),
                ('mitre_attack', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='MITRE_ATTACK')),
                ('campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CAMPAIGN')),
                ('org', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ORG')),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='COUNTRY')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CITY')),
                ('geolocation', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='GEOLOCATION')),
                ('time_stamp', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='TIMESTAMP')),
                ('ioc', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='IOC')),
                ('technique', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='TECHNIQUE')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
            options={
                'db_table': 'document_nlp_result',
            },
        ),
    ]
