# Generated by Django 3.1.5 on 2021-01-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_nlpresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlp',
            name='ocr_word_ids',
        ),
    ]
