# Generated by Django 3.1.5 on 2021-01-30 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_nlp_ocr_word_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlp',
            name='ocr_word_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
