# Generated by Django 3.1.5 on 2021-01-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_nlp_ocr_word_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.status'),
        ),
    ]
